make figures/bar_age_graph.png
make bar_age_graph.png
make figures/bar_age_graph.png
clean
make clean
make report.pdf
cd
ls
make report.pdf
make Report.pdf
docker build report.pdf
make report.pdf
make figures/bar_age_graph.png
make clean
make figures/bar_age_graph.png
make report.pdf
make Report.pdf
R -h
make Report.pdf
ls
make figures/bar_age_graph.png
make bar_sex_graph.png
make Report.pdf
make clean
make figures/bar_sex_graph.png
make Report.pdf
make figures/bar_sex_graph.png
make Report.pdf
make figures/offage_bar.png
figures/offage_bar.png
make figures/offage_bar.png
make figures/~
make clean
clean
make clean
make figures/~
make clean
make Figures/~
make clean
make Figures/~
make clean
make Derived_data/Final.csv
make clean
make Figures/~
make Derived_data/Final.csv
make clean
make Derived_data/Final.csv
make clean
make Derived_data/Final.csv
make clean
make Derived_data/Final.csv
make Figures/~
make Derived_data/Final.csv
make Figures/~
*** [Makefile:10: Figures/~] Error 1
make clean
make Figures/~
make clean
make Figures/~~
make Figures/~
make clean
make Figures/~
make clean
make Figures/~
make clean
make Figures/~
make clean
make Figures/~
make Report.pdf
make FinalProject.pdf
make clean
make Report.PDF
make Report.pdf
make Figures/~
make Report.pdf
make clean
make Figures/~
make clean
make Figures/~
make clean
make Figures/~
make clean
make Figures/~
make Report.pdf
make clean
make Figures/~
make Report.pdf
make clean
make Figures/~
make Report.pdf
make clean
make Figures/~
make Report.pdf
make clean
make Figures/~
make clena
make clean
make Figures/~
make Report.pdf
make clean
make Figures/~
make Report.pdf
make clean
make Figures/~
make Report.pdf
make clean
make Figures/~
make Report.pdf
make clean
make Figures/~
make Report.pdf
make clean
make Figures/~
make Report.pdf
make clean
make Figures/~
make Report.pdf
make clean
make Figures/~
make Report.pdf
make clean
make Figures/~
make Report.pdf
make clean
make Figures/~
make Report.pdf
make clean
make Figures/~
make Report.pdf
make clean
make Report.pdf
make Figures/~
make Report.pdf
